name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./image-classifier/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-classifier-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./image-classifier/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-classifier-frontend:latest
